name: Linux

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, ubuntu-20.04]
    steps:
    - uses: actions/checkout@v2

    - name: Build iwasm
      run: |
        cd product-mini/platforms/linux
        mkdir build && cd build
        cmake ..
        make
    - name: Classic interp
      run: |
        cd product-mini/platforms/linux
        mkdir build && cd build
        cmake .. -DWAMR_BUILD_FAST_INTERP=0
        make
    - name: Multi module
      run: |
        cd product-mini/platforms/linux
        mkdir build && cd build
        cmake .. -DWAMR_BUILD_MULTI_MODULE=1
        make
    - name: pthread
      run: |
        cd product-mini/platforms/linux
        mkdir build && cd build
        cmake .. -DWAMR_BUILD_LIB_PTHREAD=1
        make
    - name: Build wasm-c-api
      run: |
        cd samples/wasm-c-api
        mkdir build && cd build
        cmake ..
        make
        ./hello
        ./global
        ./callback
